# ==========================================
# Configuración de la Aplicación
# ==========================================
spring.application.name=ms_bff
server.port=8084

# ==========================================
# Endpoints de Microservicios Externos
# ==========================================
endpoints.ms-users=${USERS_URL:http://localhost:8081}
endpoints.ms-pets=${PETS_URL:http://localhost:8082}

# ==========================================
# Configuración de Seguridad y CORS 
# ==========================================
app.security.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}

# ==========================================
# Configuración de OAuth2 con Microsoft Entra ID
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/30702ecf-e2f2-4cb7-a22e-fa152f6ff961/
spring.security.oauth2.resourceserver.jwt.audiences=api://c538c4d3-453d-4aec-bcaa-a917b8dd245e

# ==========================================
# Mostrar errores ocultos de Spring Security
# ==========================================
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG